apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - image: nexus.build.svc.cluster.local:5000/alpine
    name: main
    command:
    - sh
    - -c
    - "while true; do echo hi; sleep 60; done"
